name: frontend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  path: ^1.9.0
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  intl: ^0.20.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  flutter_riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.6
  drift_dev: ^2.17.0
  build_runner: ^2.4.0
